services:
  nats:
    image: docker.io/library/nats:latest
    container_name: nats
    ports:
      - "4222:4222"
      - "8222:8222"
    healthcheck:
      test: ["CMD", "nats", "server", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  log-analyzer:
    build:
      context: .
      dockerfile: Dockerfile.log-analyzer
    image: log-analyzer:latest
    container_name: log-analyzer
    depends_on:
      nats:
        condition: service_healthy
    command: >
      --nats-url nats://nats:4222
      --subject logs
      --port 8080
    ports:
      - "8080:8080"

  noise-maker:
    build:
      context: .
      dockerfile: Dockerfile.noise-maker
    image: noise-maker:latest
    container_name: noise-maker
    depends_on:
      nats:
        condition: service_healthy
    command: >
      --nats-url nats://nats:4222
      --subject logs
      --rate ${RATE:-100}
      --batch-size ${BATCH_SIZE:-100000}

  prometheus:
    image: docker.io/prom/prometheus:latest
    container_name: prometheus
    depends_on:
      - log-analyzer
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: docker.io/grafana/grafana:latest
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/etc/grafana/dashboards

volumes:
  grafana-storage:
